version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "frontend"
          ContainerPort: 80
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-xxxxxxxxx"
              - "subnet-yyyyyyyyy"
            SecurityGroups:
              - "sg-zzzzzzzzz"
            AssignPublicIp: "ENABLED"
